// TRANSACTION
export const CREATE_TRANSACTION_REQUEST = "CREATE_TRANSACTION_REQUEST"
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS"
export const CREATE_TRANSACTION_FAILURE = "CREATE_TRANSACTION_FAILURE"

export const LIST_TRANSACTION_REQUEST = "LIST_TRANSACTION_REQUEST"
export const LIST_TRANSACTION_SUCCESS = "LIST_TRANSACTION_SUCCESS"
export const LIST_TRANSACTION_FAILURE = "LIST_TRANSACTION_FAILURE"
