// TRANSACTION
export const CREATE_TRANSACTION_REQUEST = "CREATE_TRANSACTION_REQUEST"
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS"
export const CREATE_TRANSACTION_FAILURE = "CREATE_TRANSACTION_FAILURE"
